name: .NET (build & publish release)

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    steps:
    - uses: actions/checkout@main

    - name: Install latest .NET 6 SDK
      uses: Elskom/setup-latest-dotnet@main
      with:
        VERSION_MAJOR: '6'
        VERSION_BAND: '4xx'

    - name: Restore, Build, Pack, and Push
      uses: Elskom/build-dotnet@main
      with:
        RESTORE: false
        PUSH: true
